# Generated by Django 5.0.4 on 2024-04-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Namiot',
            new_name='Auto',
        ),
    ]
