# Generated by Django 5.0.4 on 2024-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0002_rename_namiot_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='rozmiar',
            new_name='seats',
        ),
        migrations.RenameField(
            model_name='rezerwacja',
            old_name='namiot',
            new_name='auto',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='kolor',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='standard',
        ),
        migrations.AddField(
            model_name='auto',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'automatic'), ('MANUAL', 'manual'), ('BOTH', 'both')], default='BOTH', max_length=16),
        ),
        migrations.AddField(
            model_name='auto',
            name='type',
            field=models.CharField(choices=[('CAR', 'car'), ('VANS&TRUCKS', 'vans&trucks'), ('PREMIUM', 'premium')], default='CAR', max_length=16),
        ),
    ]
