# Generated by Django 5.0.4 on 2024-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0003_rename_rozmiar_auto_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.PositiveSmallIntegerField(default=400),
            preserve_default=False,
        ),
    ]
