# Generated by Django 5.0.4 on 2024-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0005_auto_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brand',
            field=models.CharField(max_length=25),
        ),
    ]
